name: "Release and Deploy"
on:
  push:
    branches:
      - "development"

jobs:
  release-and-deploy: 
    runs-on: "ubuntu-20.04"
    steps: 
      - name: "Checkout code"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
      - name: "Set up Node environment"
        uses: "actions/setup-node@v2"
        with:
          node-version: '14'
      - name: "Install dependencies"
        run: "npm install"
      - name: "Release code"
        run: "npm run release -- --ci"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: "Deploy web app"
        run: "npm run deploy"
