name: "Release"
on:
  push:
    branches:
      - "development"

jobs:
  release: 
    runs-on: "ubuntu-20.04"
    steps: 
      - name: "Checkout code"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
      - name: "Set up Node environment"
        uses: "actions/setup-node@v2"
        with:
          node-version: '14'
      - name: "Install dependencies"
        run: "npm install"
      - name: "Set up git user email"
        run: "git config --global user.email 'maciej.laciak@gmail.com'"
      - name: "Set up git user name" 
        run: "git config --global user.name 'mstream'"
      - name: "Release code"
        run: "npm run release"
      - name: "Push changes"
        run: "git push --follow-tags origin development"
